import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';

export default function Home({ allPosts }) {
	// console.log(allPosts);
	const [postsState, setPostsState] = useState([]);
	const [title, setTitle] = useState('');
	const [content, setContent] = useState('');
	const [loading, setLoading] = useState(false);

	useEffect(() => {
		setPostsState(allPosts.data);
	}, []);

	const handleAddPost = async (e) => {
		setLoading(true);
		const newPost = await fetch('http://localhost:3000/api/posts', {
			method: 'POST',
			body: JSON.stringify({
				title: title,
				content: content
			})
		});
		newPost = await newPost.json();
		console.log(newPost);
		setPostsState([
			...postsState,
			{
				title,
				content
			}
		]);
		setTitle('');
		setContent('');
		setLoading(false);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>NextJS MongoDB</h1>
				<br />
				<div>
					<input
						type="text"
						value={title}
						onChange={(e) => setTitle(e.target.value)}
					/>
					<input
						type="text"
						value={content}
						onChange={(e) => setContent(e.target.value)}
					/>
					<button disabled={loading} onClick={handleAddPost}>
						Add
					</button>
				</div>
				<br />
				{postsState?.map((post, idx) => (
					<div key={idx}>
						<h3>{post.title}</h3>
						<h5>{post.content}</h5>
					</div>
				))}
			</main>
		</div>
	);
}

export const getServerSideProps = async () => {
	const res = await fetch('http://localhost:3000/api/posts', {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json'
		}
	});
	let allPosts = await res.json();

	return {
		props: {
			allPosts
		}
	};
};
